# Generated by Django 4.0.5 on 2022-06-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_remove_audiokniga_audio_url2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiokniga',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
