# Generated by Django 4.0.5 on 2022-06-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='book_name',
        ),
    ]
