# Generated by Django 4.0.5 on 2022-06-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_wish_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='book_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
